name: Dev - Deploy API Management

on:
 workflow_dispatch:
 push:
   branches:
     - main

jobs:
  deploy-web-app-dev:
    runs-on: ubuntu-latest
    environment: Development
    env:
      TERRAFORM_MODULE_VERSION: 6.4.2
      TERRAFORM_ENVIRONMENT: dev
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Add nuget feed
      run: |
        dotnet nuget add source --username ${{ secrets.PACKAGE_USER }} --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/airslip-ltd/index.json"
        nuget sources add -name "github" -Source "https://nuget.pkg.github.com/airslip-ltd/index.json" -UserName ${{ secrets.PACKAGE_USER }} -Password ${{ secrets.PACKAGE_TOKEN }} -StorePasswordInClearTex
    - name: Install Terraform Modules
      run: nuget install Airslip.Terraform.Modules -Version ${{ env.TERRAFORM_MODULE_VERSION }} -OutputDirectory ./env/tf_modules -x

    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["./env/variables/secrets.tfvars"]'
      env:
        RELEASE_NAME: v${{ github.run_id }}
      
    - name: Terraform Update
      id: "terraform_update"
      env:
        ARM_CLIENT_ID: ${{ secrets.NON_PROD_ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.NON_PROD_ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.NON_PROD_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.NON_PROD_ARM_TENANT_ID }}
      run: |
        terraform init -backend-config=variables/${{ env.TERRAFORM_ENVIRONMENT }}/backend.tfvars
        terraform plan -var-file=variables/${{ env.TERRAFORM_ENVIRONMENT }}/variables.tfvars -var-file=variables/secrets.tfvars -out=terraform.tfplan
        terraform apply terraform.tfplan
      working-directory: ./env